version: '3'

networks:
  rabbitmq-network:
    driver: bridge

services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/run/secrets/rabbit_config"
    secrets:
      - rabbit_config
    networks:
      - rabbitmq-network

  gen_4:
    image: bot-ica:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - BOT_PROPERTY_FILE_PATH=/app/volume/src/main/resources/ConfigurationFiles/gen_4.properties
    networks:
      - rabbitmq-network
    volumes:
      - botica-volume:/app/volume
    depends_on:
      - rabbitmq
    restart: unless-stopped


  ex_1:
    image: bot-ica:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - BOT_PROPERTY_FILE_PATH=/app/volume/src/main/resources/ConfigurationFiles/ex_1.properties
    networks:
      - rabbitmq-network
    volumes:
      - botica-volume:/app/volume
    depends_on:
      - rabbitmq
    restart: unless-stopped


  re_1:
    image: bot-ica:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - BOT_PROPERTY_FILE_PATH=/app/volume/src/main/resources/ConfigurationFiles/re_1.properties
    networks:
      - rabbitmq-network
    volumes:
      - botica-volume:/app/volume
    depends_on:
      - rabbitmq
    restart: unless-stopped

volumes:
  botica-volume:
  
secrets:
  rabbit_config:
    file: ./rabbitmq/definitions.json