package com.botica.launchers;

import static es.us.isa.restest.util.FileManager.createDir;
import static es.us.isa.restest.util.FileManager.deleteDir;

import java.util.Properties;

import org.json.JSONObject;

import es.us.isa.restest.runners.RESTestExecutor;

/**
 * This class is a launcher for executing test cases generated by generators.
 */
public class TestCaseExecutorLauncher extends AbstractLauncher{

    private static final String PROPERTY_FILE_PATH_JSON_KEY = "propertyFilePath";
    private static final String TEST_CASES_PATH = "testCasesPath";

    public TestCaseExecutorLauncher(String keyToPublish, String orderToPublish, Properties botProperties) {
        super(keyToPublish, orderToPublish, botProperties);
    }

    /**
     * Executes test cases generated.
     */
    @Override
    protected void botAction() {

        String propertyFilePath = messageData.getString(PROPERTY_FILE_PATH_JSON_KEY);

        RESTestExecutor executor = new RESTestExecutor(propertyFilePath, true);

        // TODO: Check if is correct
        // Create directories to store test data extracted from the execution
        String experimentName = PropertyReader.readProperty(propertyFilePath, "experiment.name");

        String testDataDir = PropertyReader.readProperty(propertyFilePath, "data.tests.dir") + "/" + experimentName;
        String coverageDataDir = PropertyReader.readProperty(propertyFilePath, "data.coverage.dir") + "/" + experimentName;
        String allureResultsDir = PropertyReader.readProperty(propertyFilePath, "allure.results.dir") + "/" + experimentName;
        String allureReportDir = PropertyReader.readProperty(propertyFilePath, "allure.report.dir") + "/" + experimentName;

        String deletePreviousResults = PropertyReader.readProperty(propertyFilePath, "deletepreviousresults");
        if (deletePreviousResults != null && Boolean.parseBoolean(deletePreviousResults)) {
            deleteDir(testDataDir);
            deleteDir(coverageDataDir);
            deleteDir(allureResultsDir);
            deleteDir(allureReportDir);
        }

        createDir(testDataDir);
        createDir(coverageDataDir);
        //

        auxBotAction(executor, propertyFilePath);
    }

    private void auxBotAction(RESTestExecutor executor, String propertyFilePath) {
        String allureResultsDirPath = PropertyReader.readProperty(propertyFilePath, "allure.results.dir");
        String experimentName = PropertyReader.readProperty(propertyFilePath, "experiment.name");
        System.setProperty("allure.results.directory", allureResultsDirPath + "/" + experimentName);
        executor.execute();
    }

    @Override
    protected JSONObject createMessage() {

        String propertyFilePath = messageData.getString(PROPERTY_FILE_PATH_JSON_KEY);
        String testCasesPath = messageData.getString(TEST_CASES_PATH);

        JSONObject message = new JSONObject();
        message.put("order", this.orderToPublish);
        message.put(PROPERTY_FILE_PATH_JSON_KEY, propertyFilePath);
        message.put(TEST_CASES_PATH, testCasesPath);

        return message;
    }
}
