bots:
  my-bot:
    image: "my-bot-container-image:latest"
    replicas: 2
    mount: # Optional section
      - source: "path/to/host/file.extension"
        target: "path/to/container/file.extension"
      - source: "path/to/host/directory"
        target: "path/to/container/directory"
        createHostPath: true # This creates "path/to/host/directory" if it does not exist
    lifecycle: # Optional section
      type: proactive
      period: 60 # In seconds
    environment: # Optional section
      - KEY1=VALUE2
      - KEY2=VALUE2

  my-other-bot:
    image: "my-other-bot-container-image:latest"
    ports:
      - "8000:8000"
    subscribe: # Optional section
      - key: "tasks"
        strategy: distributed # Each message sent to this key will be received by only one random available instance of this bot type
      - key: "news"
        strategy: broadcast # Each message sent to this key will be received by all instances of this bot type
    # Missing lifecycle section - default is "reactive"
    environment: # Optional section
      - KEY1=VALUE2
      - KEY2=VALUE2
    instances: # Instead of "replicas: 3"
      my-other-bot-1:
        environment:
          - KEY3=VALUE3
      my-other-bot-2:
        environment:
          - KEY2=OVERRIDEN_VALUE
      my-other-bot-3: { }

  database:
    image: "my-database-image:latest"
    mount: # Optional section
      - source: "path/to/host/directory"
        target: "path/to/container/directory"
        createHostPath: true # This creates "path/to/host/directory" if it does not exist
    lifecycle:
      # Important - this is not a Botica bot.
      # The "unmanaged" lifecycle type tells Botica Director to ignore it as a bot.
      # However, other bots can access the database instance through their private network.
      # Just use the corresponding method to resolve the container hostname from your programming language's Botica library.
      #
      # Examples:
      #   - Java: this.getBotHostname("database"); (inside BaseBot)
      #   - Node.js: bot.getBotHostname("database");
      type: unmanaged
    environment:
      - KEY=VALUE
    instances:
      database: { }
