package es.us.isa.botica.director.broker;

import static es.us.isa.botica.rabbitmq.RabbitMqConstants.ORDER_EXCHANGE;
import static es.us.isa.botica.rabbitmq.RabbitMqConstants.PROTOCOL_EXCHANGE;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import es.us.isa.botica.configuration.MainConfiguration;
import es.us.isa.botica.configuration.bot.BotSubscribeConfiguration;
import es.us.isa.botica.configuration.bot.BotSubscribeConfiguration.RoutingStrategy;
import es.us.isa.botica.configuration.bot.BotTypeConfiguration;
import es.us.isa.botica.configuration.broker.RabbitMqConfiguration;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class RabbitMqConfigurationGeneratorTest {
  @TempDir Path tempDir;

  private static final String DEFAULT_USERNAME = "testuser";
  private static final String DEFAULT_PASSWORD = "testpassword";

  private final ObjectMapper objectMapper = new ObjectMapper();

  @Test
  @DisplayName(
      "generateDefinitionsFile should create a non-empty definitions file "
          + "matching the content generated by buildDefinitionsContent")
  void generateDefinitionsFile_createsFileMatchingBuildDefinitionsContent() throws IOException {
    // Arrange
    MainConfiguration testConfiguration = buildDefaultMainConfiguration();
    RabbitMqConfigurationGenerator configurationGenerator =
        new RabbitMqConfigurationGenerator(testConfiguration);
    Path definitionsFilePath = tempDir.resolve("definitions.json");
    String expectedContent = configurationGenerator.buildDefinitionsContent();

    // Act
    configurationGenerator.generateDefinitionsFile(definitionsFilePath);

    // Assert
    assertThat(definitionsFilePath).exists().isNotEmptyFile();
    String fileContent = Files.readString(definitionsFilePath, StandardCharsets.UTF_8);
    assertThat(fileContent).isEqualToNormalizingNewlines(expectedContent);
  }

  @Test
  @DisplayName("buildDefinitionsContent should generate valid and parseable JSON")
  void buildDefinitionsContent_generatesValidAndParseableJson() {
    // Arrange
    MainConfiguration testConfiguration = buildDefaultMainConfiguration();
    RabbitMqConfigurationGenerator configurationGenerator =
        new RabbitMqConfigurationGenerator(testConfiguration);

    // Act & Assert
    assertThatCode(() -> objectMapper.readTree(configurationGenerator.buildDefinitionsContent()))
        .doesNotThrowAnyException();
  }

  @Test
  @DisplayName("buildDefinitionsContent should contain correct user authentication and permissions")
  void buildDefinitionsContent_containsCorrectUserAuthenticationAndPermissions()
      throws IOException {
    // Arrange
    MainConfiguration testConfiguration = buildDefaultMainConfiguration();
    RabbitMqConfigurationGenerator configurationGenerator =
        new RabbitMqConfigurationGenerator(testConfiguration);

    // Act
    String content = configurationGenerator.buildDefinitionsContent();
    JsonNode rootNode = objectMapper.readTree(content);

    // Assert Users
    JsonNode usersNode = rootNode.path("users");
    assertThat(usersNode).hasSize(1);
    JsonNode userNode = usersNode.get(0);
    assertThat(userNode.path("name").asText()).isEqualTo(DEFAULT_USERNAME);
    assertThat(userNode.path("password").asText()).isEqualTo(DEFAULT_PASSWORD);
    assertThat(userNode.path("tags").asText()).isEqualTo("administrator");

    // Assert Permissions
    JsonNode permissionsNode = rootNode.path("permissions");
    assertThat(permissionsNode.isArray()).isTrue();
    assertThat(permissionsNode).hasSize(1);
    JsonNode permissionNode = permissionsNode.get(0);
    assertThat(permissionNode.path("user").asText()).isEqualTo(DEFAULT_USERNAME);
    assertThat(permissionNode.path("vhost").asText()).isEqualTo("/");
    assertThat(permissionNode.path("configure").asText()).isEqualTo(".*");
    assertThat(permissionNode.path("write").asText()).isEqualTo(".*");
    assertThat(permissionNode.path("read").asText()).isEqualTo(".*");
  }

  @Test
  @DisplayName(
      "buildDefinitionsContent should contain correct queue definitions for bot types and strategies")
  void buildDefinitionsContent_containsCorrectQueues() throws IOException {
    // Arrange
    MainConfiguration testConfiguration = buildDefaultMainConfiguration();
    RabbitMqConfigurationGenerator configurationGenerator =
        new RabbitMqConfigurationGenerator(testConfiguration);

    // Act
    String content = configurationGenerator.buildDefinitionsContent();
    JsonNode rootNode = objectMapper.readTree(content);

    // Assert
    JsonNode queuesNode = rootNode.path("queues");
    assertThat(queuesNode.isArray()).isTrue();
    assertThat(queuesNode).hasSize(3);

    // Queue 1: bot_type.foo.orders.distributed
    JsonNode queue1 = queuesNode.get(0);
    assertThat(queue1.path("name").asText()).isEqualTo("bot_type.foo.orders.distributed");
    assertThat(queue1.path("vhost").asText()).isEqualTo("/");
    assertThat(queue1.path("durable").asBoolean()).isTrue();
    assertThat(queue1.path("auto_delete").asBoolean()).isFalse();
    assertThat(queue1.path("arguments").isEmpty()).isTrue(); // Not a stream queue

    // Queue 2: bot_type.bar.orders.distributed
    JsonNode queue2 = queuesNode.get(1);
    assertThat(queue2.path("name").asText()).isEqualTo("bot_type.bar.orders.distributed");
    assertThat(queue2.path("vhost").asText()).isEqualTo("/");
    assertThat(queue2.path("durable").asBoolean()).isTrue();
    assertThat(queue2.path("auto_delete").asBoolean()).isFalse();
    assertThat(queue2.path("arguments").isEmpty()).isTrue(); // Not a stream queue

    // Queue 3: bot_type.bar.orders.broadcast (stream queue)
    JsonNode queue3 = queuesNode.get(2);
    assertThat(queue3.path("name").asText()).isEqualTo("bot_type.bar.orders.broadcast");
    assertThat(queue3.path("vhost").asText()).isEqualTo("/");
    assertThat(queue3.path("durable").asBoolean()).isTrue();
    assertThat(queue3.path("auto_delete").asBoolean()).isFalse();
    assertThat(queue3.path("arguments").path("x-queue-type").asText()).isEqualTo("stream");
  }

  @Test
  @DisplayName("buildDefinitionsContent should contain required exchange definitions")
  void buildDefinitionsContent_containsCorrectExchanges() throws IOException {
    // Arrange
    MainConfiguration testConfiguration = buildDefaultMainConfiguration();
    RabbitMqConfigurationGenerator configurationGenerator =
        new RabbitMqConfigurationGenerator(testConfiguration);

    // Act
    String content = configurationGenerator.buildDefinitionsContent();
    JsonNode rootNode = objectMapper.readTree(content);

    // Assert
    JsonNode exchangesNode = rootNode.path("exchanges");
    assertThat(exchangesNode.isArray()).isTrue();
    assertThat(exchangesNode).hasSize(2);

    // Exchange 1: ORDER_EXCHANGE
    JsonNode exchange1 = exchangesNode.get(0);
    assertThat(exchange1.path("name").asText()).isEqualTo(ORDER_EXCHANGE);
    assertThat(exchange1.path("vhost").asText()).isEqualTo("/");
    assertThat(exchange1.path("type").asText()).isEqualTo("topic");
    assertThat(exchange1.path("durable").asBoolean()).isTrue();
    assertThat(exchange1.path("auto_delete").asBoolean()).isFalse();
    assertThat(exchange1.path("internal").asBoolean()).isFalse();
    assertThat(exchange1.path("arguments").isEmpty()).isTrue();

    // Exchange 2: PROTOCOL_EXCHANGE
    JsonNode exchange2 = exchangesNode.get(1);
    assertThat(exchange2.path("name").asText()).isEqualTo(PROTOCOL_EXCHANGE);
    assertThat(exchange2.path("vhost").asText()).isEqualTo("/");
    assertThat(exchange2.path("type").asText()).isEqualTo("topic");
    assertThat(exchange2.path("durable").asBoolean()).isTrue();
    assertThat(exchange2.path("auto_delete").asBoolean()).isFalse();
    assertThat(exchange2.path("internal").asBoolean()).isFalse();
    assertThat(exchange2.path("arguments").isEmpty()).isTrue();
  }

  @Test
  @DisplayName("buildDefinitionsContent should contain correct binding definitions")
  void buildDefinitionsContent_containsCorrectBindings() throws IOException {
    // Arrange
    MainConfiguration testConfiguration = buildDefaultMainConfiguration();
    RabbitMqConfigurationGenerator configurationGenerator =
        new RabbitMqConfigurationGenerator(testConfiguration);

    // Act
    String content = configurationGenerator.buildDefinitionsContent();
    JsonNode rootNode = objectMapper.readTree(content);

    // Assert
    JsonNode bindingsNode = rootNode.path("bindings");
    assertThat(bindingsNode.isArray()).isTrue();
    assertThat(bindingsNode).hasSize(4);

    // Binding 1: bot_type.foo.orders.distributed, foo_key
    JsonNode binding1 = bindingsNode.get(0);
    assertThat(binding1.path("source").asText()).isEqualTo(ORDER_EXCHANGE);
    assertThat(binding1.path("vhost").asText()).isEqualTo("/");
    assertThat(binding1.path("destination").asText()).isEqualTo("bot_type.foo.orders.distributed");
    assertThat(binding1.path("destination_type").asText()).isEqualTo("queue");
    assertThat(binding1.path("routing_key").asText()).isEqualTo("foo_key");
    assertThat(binding1.path("arguments").isEmpty()).isTrue();

    // Binding 2: bot_type.foo.orders.distributed, bar_key
    JsonNode binding2 = bindingsNode.get(1);
    assertThat(binding2.path("source").asText()).isEqualTo(ORDER_EXCHANGE);
    assertThat(binding2.path("vhost").asText()).isEqualTo("/");
    assertThat(binding2.path("destination").asText()).isEqualTo("bot_type.foo.orders.distributed");
    assertThat(binding2.path("destination_type").asText()).isEqualTo("queue");
    assertThat(binding2.path("routing_key").asText()).isEqualTo("bar_key");
    assertThat(binding2.path("arguments").isEmpty()).isTrue();

    // Binding 3: bot_type.bar.orders.distributed, bar_key
    JsonNode binding3 = bindingsNode.get(2);
    assertThat(binding3.path("source").asText()).isEqualTo(ORDER_EXCHANGE);
    assertThat(binding3.path("vhost").asText()).isEqualTo("/");
    assertThat(binding3.path("destination").asText()).isEqualTo("bot_type.bar.orders.distributed");
    assertThat(binding3.path("destination_type").asText()).isEqualTo("queue");
    assertThat(binding3.path("routing_key").asText()).isEqualTo("bar_key");
    assertThat(binding3.path("arguments").isEmpty()).isTrue();

    // Binding 4: bot_type.bar.orders.broadcast, qux_key
    JsonNode binding4 = bindingsNode.get(3);
    assertThat(binding4.path("source").asText()).isEqualTo(ORDER_EXCHANGE);
    assertThat(binding4.path("vhost").asText()).isEqualTo("/");
    assertThat(binding4.path("destination").asText()).isEqualTo("bot_type.bar.orders.broadcast");
    assertThat(binding4.path("destination_type").asText()).isEqualTo("queue");
    assertThat(binding4.path("routing_key").asText()).isEqualTo("qux_key");
    assertThat(binding4.path("arguments").isEmpty()).isTrue();
  }

  @Test
  @DisplayName(
      "buildDefinitionsContent should generate correct JSON when no bot types are configured")
  void buildDefinitionsContent_noBotTypes_generatesCorrectJson() throws IOException {
    // Arrange
    MainConfiguration emptyConfiguration = new MainConfiguration();
    RabbitMqConfiguration rabbitConfiguration = new RabbitMqConfiguration();
    rabbitConfiguration.setUsername(DEFAULT_USERNAME);
    rabbitConfiguration.setPassword(DEFAULT_PASSWORD);
    emptyConfiguration.setBrokerConfiguration(rabbitConfiguration);
    emptyConfiguration.setBotTypes(Collections.emptyMap());

    RabbitMqConfigurationGenerator configurationGenerator =
        new RabbitMqConfigurationGenerator(emptyConfiguration);

    // Act
    String content = configurationGenerator.buildDefinitionsContent();
    JsonNode rootNode = objectMapper.readTree(content);

    // Assert base structure
    assertThat(rootNode.path("vhosts")).hasSize(1);
    assertThat(rootNode.path("users")).hasSize(1);
    assertThat(rootNode.path("permissions")).hasSize(1);
    assertThat(rootNode.path("exchanges")).hasSize(2); // Still has default exchanges

    // Assert that queues and bindings are empty arrays
    assertThat(rootNode.path("queues")).isEmpty();
    assertThat(rootNode.path("bindings")).isEmpty();

    // Assert user details are still present
    assertThat(rootNode.path("users").get(0).path("name").asText()).isEqualTo(DEFAULT_USERNAME);
    assertThat(rootNode.path("users").get(0).path("password").asText()).isEqualTo(DEFAULT_PASSWORD);
  }

  @Test
  @DisplayName(
      "buildDefinitionsContent should correctly handle a single bot type with mixed strategies")
  void buildDefinitionsContent_singleBotTypeMixedStrategies_generatesCorrectJson()
      throws IOException {
    // Arrange
    MainConfiguration config = new MainConfiguration();
    RabbitMqConfiguration rabbitConfig = new RabbitMqConfiguration();
    rabbitConfig.setUsername(DEFAULT_USERNAME);
    rabbitConfig.setPassword(DEFAULT_PASSWORD);
    config.setBrokerConfiguration(rabbitConfig);

    BotTypeConfiguration singleBotType = new BotTypeConfiguration();
    singleBotType.setId("singleBot");

    BotSubscribeConfiguration distributedSub = new BotSubscribeConfiguration();
    distributedSub.setKey("dist_key");
    distributedSub.setStrategy(RoutingStrategy.DISTRIBUTED);

    BotSubscribeConfiguration broadcastSub = new BotSubscribeConfiguration();
    broadcastSub.setKey("broadcast_key");
    broadcastSub.setStrategy(RoutingStrategy.BROADCAST);

    singleBotType.setSubscribeConfigurations(List.of(distributedSub, broadcastSub));
    config.setBotTypes(Map.of("singleBot", singleBotType));

    RabbitMqConfigurationGenerator generator = new RabbitMqConfigurationGenerator(config);

    // Act
    String content = generator.buildDefinitionsContent();
    JsonNode rootNode = objectMapper.readTree(content);

    // Assert Queues
    JsonNode queuesNode = rootNode.path("queues");
    assertThat(queuesNode).hasSize(2);

    JsonNode distributedQueue = queuesNode.get(0);
    assertThat(distributedQueue.path("name").asText())
        .isEqualTo("bot_type.singleBot.orders.distributed");
    assertThat(distributedQueue.path("arguments").isEmpty()).isTrue();

    JsonNode broadcastQueue = queuesNode.get(1);
    assertThat(broadcastQueue.path("name").asText())
        .isEqualTo("bot_type.singleBot.orders.broadcast");
    assertThat(broadcastQueue.path("arguments").path("x-queue-type").asText()).isEqualTo("stream");

    // Assert Bindings
    JsonNode bindingsNode = rootNode.path("bindings");
    assertThat(bindingsNode).hasSize(2);

    JsonNode distributedBinding = bindingsNode.get(0);
    assertThat(distributedBinding.path("source").asText()).isEqualTo(ORDER_EXCHANGE);
    assertThat(distributedBinding.path("destination").asText())
        .isEqualTo("bot_type.singleBot.orders.distributed");
    assertThat(distributedBinding.path("routing_key").asText()).isEqualTo("dist_key");

    JsonNode broadcastBinding = bindingsNode.get(1);
    assertThat(broadcastBinding.path("source").asText()).isEqualTo(ORDER_EXCHANGE);
    assertThat(broadcastBinding.path("destination").asText())
        .isEqualTo("bot_type.singleBot.orders.broadcast");
    assertThat(broadcastBinding.path("routing_key").asText()).isEqualTo("broadcast_key");
  }

  private MainConfiguration buildDefaultMainConfiguration() {
    MainConfiguration configuration = new MainConfiguration();

    RabbitMqConfiguration rabbitConfiguration = new RabbitMqConfiguration();
    rabbitConfiguration.setUsername(DEFAULT_USERNAME);
    rabbitConfiguration.setPassword(DEFAULT_PASSWORD);

    configuration.setBrokerConfiguration(rabbitConfiguration);
    configuration.setBotTypes(buildBotConfigurations());
    return configuration;
  }

  private Map<String, BotTypeConfiguration> buildBotConfigurations() {
    var fooKeySubscription = buildSubscription("foo_key", RoutingStrategy.DISTRIBUTED);
    var barKeySubscription = buildSubscription("bar_key", RoutingStrategy.DISTRIBUTED);
    var quxKeySubscription = buildSubscription("qux_key", RoutingStrategy.BROADCAST);

    BotTypeConfiguration fooBotType = new BotTypeConfiguration();
    fooBotType.setId("foo");
    fooBotType.setSubscribeConfigurations(List.of(fooKeySubscription, barKeySubscription));

    BotTypeConfiguration barBotType = new BotTypeConfiguration();
    barBotType.setId("bar");
    barBotType.setSubscribeConfigurations(List.of(barKeySubscription, quxKeySubscription));

    Map<String, BotTypeConfiguration> bots =
        new LinkedHashMap<>(); // Use LinkedHashMap for predictable order in tests
    bots.put("foo", fooBotType);
    bots.put("bar", barBotType);
    return bots;
  }

  private BotSubscribeConfiguration buildSubscription(String key, RoutingStrategy strategy) {
    BotSubscribeConfiguration subscribeConfiguration = new BotSubscribeConfiguration();
    subscribeConfiguration.setKey(key);
    subscribeConfiguration.setStrategy(strategy);
    return subscribeConfiguration;
  }
}
